# Generated by Django 4.0.2 on 2022-02-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygame',
            old_name='player_id',
            new_name='category_id',
        ),
    ]
