# Generated by Django 4.0.2 on 2022-02-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0004_alter_categorygame_category_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygame',
            old_name='category_type',
            new_name='category_type_id',
        ),
    ]
