# Generated by Django 4.0.2 on 2022-02-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameraterapi', '0005_rename_category_type_categorygame_category_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygame',
            old_name='category_type_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='categorygame',
            old_name='game_id',
            new_name='game',
        ),
    ]
